# Generated by Django 3.2.8 on 2021-11-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='product/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=60)),
            ],
        ),
    ]
